skip_docs

before_all do |lane, options|
end

platform :ios do
  lane :build do |options|
  end

  lane :deploy do |options|
    ipa = options[:ipa]
    release_note = options[:release_note]
    ios_deploy(ipa: ipa, release_note: release_note)
  end

  lane :test do |options|
  end
end

platform :android do
  lane :build do |options|
  end

  lane :deploy do |options|
    apk = options[:apk]
    release_note = options[:release_note]
    android_deploy(apk: apk, release_note: release_note)
  end

  lane :test do |options|
  end
end

after_all do |lane, options|
end

error do |lane, exception, options|
end
